# Generated by Django 6.0.3 on 2026-04-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mealentry_calories_per_100g_mealentry_carbs_per_100g_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin')], default='USER', max_length=20),
        ),
    ]
