# Generated by Django 6.0.3 on 2026-04-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
